[workspace]
members  = ["apps/*"]
resolver = "3"

[workspace.package]
authors     = ["acgxv <xv@acg.box>"]
description = "Command-line DDC/CI volume control for an external LG display on macOS."
edition     = "2024"
homepage    = "https://github.com/acg-box/deskhelm"
license     = "GPL-3.0-only"
repository  = "https://github.com/acg-box/deskhelm"
version     = "0.1.0"

[profile.final-release]
inherits = "release"
lto      = true

[workspace.dependencies]
# crates.io
clap                = { version = "4.6", features = ["derive"] }
color-eyre          = { version = "0.6" }
core-foundation-sys = { version = "0.8" }
core-graphics       = { version = "=0.24.0" }
io-kit-sys          = { version = "=0.5.0" }
